Automates release and version checks.
Refactors the release workflow to automate version checking and release creation.

It removes the manual version comparison against git tags and introduces automated checks to ensure that the package version is incremented correctly.
The workflow now uses the package.json version to create the release tag.
Also makes release pre-release.

Adds support for ubuntu-arm platform in matrix build.

diff --git a/.github/workflows/publish_and_create_version_tag.yml b/.github/workflows/publish_and_create_version_tag.yml
--- a/.github/workflows/publish_and_create_version_tag.yml
+++ b/.github/workflows/publish_and_create_version_tag.yml
@@ -2,9 +2,6 @@ name: "publish with version tag"
 
 on:
   workflow_dispatch:
-  push:
-    tags:
-      - "fusou-v*"
 
 jobs:
   create-release:
@@ -28,17 +25,6 @@ jobs:
       - name: get version
         run: |
           echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
-          echo ${{ github.ref_name }} | sed -e 's/^fusou-v//' | xargs -I {} echo "TAG_VERSION={}" >> "$GITHUB_ENV"
-
-      - name: compare version
-        run: |
-          echo "Package version: $PACKAGE_VERSION"
-          echo "Tag version: $TAG_VERSION"
-          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
-            echo "Error: Package version and Tag version do not match."
-            exit 1
-          fi
-          echo "Version check passed."
 
       - name: Get previous tag
         uses: actions/github-script@v7
@@ -50,24 +36,44 @@ jobs:
               repo: context.repo.repo,
               per_page: 2
             })
-            const previousTag = previousTags.data.length > 1 ? previousTags.data[1].name : '';
+            const previousTag = previousTags.data.length > 0 ? previousTags.data[0].name : '';
 
             return previousTag
           result-encoding: string
+
+      - name: check version
+        env:
+          PREVIOUS_TAG: ${{ steps.get-previous.outputs.result }}
+        run: |
+          current_patch_version=$(echo $PACKAGE_VERSION | sed -e 's/^[0-9]*\.[0-9]*\.//')
+          current_minor_version=$(echo $PACKAGE_VERSION | sed -e 's/^[0-9]*\.//;s/\.[0-9]*$//')
+          current_major_version=$(echo $PACKAGE_VERSION | sed -e 's/\.[0-9]*\.[0-9]*$//')
+
+          previous_patch_version=$(echo $PREVIOUS_TAG | sed -e 's/^fusou-v//' -e 's/^[0-9]*\.[0-9]*\.//')
+          previous_minor_version=$(echo $PREVIOUS_TAG | sed -e 's/^fusou-v//' -e 's/^[0-9]*\.//;s/\.[0-9]*$//')
+          previous_major_version=$(echo $PREVIOUS_TAG | sed -e 's/^fusou-v//' -e 's/\.[0-9]*\.[0-9]*$//')
+
+          if [ "$current_major_version" -lt "$previous_major_version" ]; then
+            echo "Error: Major version decreased from $previous_major_version to $current_major_version."
+            exit 1
+          elif [ "$current_major_version" -eq "$previous_major_version" ] && [ "$current_minor_version" -lt "$previous_minor_version" ]; then
+            echo "Error: Minor version decreased from $previous_minor_version to $current_minor_version."
+            exit 1
+          elif [ "$current_major_version" -eq "$previous_major_version" ] && [ "$current_minor_version" -eq "$previous_minor_version" ] && [ "$current_patch_version" -le "$previous_patch_version" ]; then
+            echo "Error: Patch version did not increase from $previous_patch_version to $current_patch_version."
+            exit 1
+          fi
+          echo "Version check passed."
 
       - name: create release
         id: create-release
         uses: actions/github-script@v6
         env:
           PREVIOUS_TAG: ${{ steps.get-previous.outputs.result }}
-          RELEASE_TAG: ${{ github.ref_name }}
         with:
           script: |
             const previousTag = process.env.PREVIOUS_TAG;
-            const releaseTag = process.env.RELEASE_TAG;
-
-            console.log(`Previous tag: ${previousTag}`);
-            console.log(`Release tag: ${releaseTag}`);
+            const releaseTag = `fusou-v${process.env.PACKAGE_VERSION}`;
 
             const releaseNotesParams = {
               owner: context.repo.owner,
@@ -88,7 +94,7 @@ jobs:
               name: `FUSOU v${process.env.PACKAGE_VERSION}`,
               body: releaseNotes.data.body,
               draft: true,
-              prerelease: false
+              prerelease: true
             });
             return data.id
 
@@ -109,8 +115,8 @@ jobs:
           #     args: "--target x86_64-apple-darwin"
           - platform: "ubuntu-24.04"
             args: ""
-          # - platform: "ubuntu-24.04-arm"
-          #   args: ""
+          - platform: "ubuntu-24.04-arm"
+            args: ""
           - platform: "windows-latest"
             args: ""
 
